// src/config/worlds.config.js
// 10 Themed Worlds for EquationQuest (Grade 7 / Secondary 1 Mathematics)

export const WORLDS = [
  {
    id: 0,
    name: "The Mystery Letter",
    emoji: "👻",
    accent: "var(--world-0)",
    description: "Translate worded phrases into algebraic expressions",
    conceptFocus: "translate-expressions",
    boss: { name: "The Phrase Phantom", emoji: "👻", reward: "Cipher Badge" },
  },
  {
    id: 1,
    name: "The Balance Case",
    emoji: "⚖️",
    accent: "var(--world-1)",
    description: "Solve one-step equations with the balance method",
    conceptFocus: "one-step-equations",
    boss: { name: "The Scale Tipper", emoji: "⚖️", reward: "Balance Badge" },
  },
  {
    id: 2,
    name: "The Two-Step Trail",
    emoji: "🎭",
    accent: "var(--world-2)",
    description: "Solve two-step equations (ax + b = c)",
    conceptFocus: "two-step-equations",
    boss: { name: "Double Trouble Dan", emoji: "🎭", reward: "Trailblazer Badge" },
  },
  {
    id: 3,
    name: "The Bracket Vault",
    emoji: "🔓",
    accent: "var(--world-3)",
    description: "Solve equations requiring bracket expansion",
    conceptFocus: "bracket-equations",
    boss: { name: "The Bracket Bandit", emoji: "🔓", reward: "Vault Cracker Badge" },
  },
  {
    id: 4,
    name: "The Fraction Files",
    emoji: "🗂️",
    accent: "var(--world-4)",
    description: "Solve equations containing a simple fraction",
    conceptFocus: "fraction-equations",
    boss: { name: "Fraction Fiona", emoji: "🗂️", reward: "Files Closed Badge" },
  },
  {
    id: 5,
    name: "Coins & Clues",
    emoji: "🪙",
    accent: "var(--world-5)",
    description: "Form and solve equations from money scenarios",
    conceptFocus: "money-word-problems",
    boss: { name: "The Coin Counterfeiter", emoji: "🪙", reward: "Treasury Badge" },
  },
  {
    id: 6,
    name: "Ages & Alibis",
    emoji: "🕰️",
    accent: "var(--world-6)",
    description: "Form and solve equations from age scenarios",
    conceptFocus: "age-word-problems",
    boss: { name: "The Age-Old Alibi", emoji: "🕰️", reward: "Timeline Badge" },
  },
  {
    id: 7,
    name: "Perimeter Puzzle",
    emoji: "📐",
    accent: "var(--world-7)",
    description: "Perimeter and consecutive-integer word problems",
    conceptFocus: "geometry-consecutive-word-problems",
    boss: { name: "The Perimeter Prowler", emoji: "📐", reward: "Blueprint Badge" },
  },
  {
    id: 8,
    name: "Detective's Verdict",
    emoji: "🧩",
    accent: "var(--world-8)",
    description: "Full multi-step applied word problems",
    conceptFocus: "multi-step-applied-word-problems",
    boss: { name: "The Case Cracker", emoji: "🧩", reward: "Verdict Badge" },
  },
  {
    id: 9,
    name: "The Grand Case File",
    emoji: "🎩",
    accent: "var(--world-9)",
    description: "Mixed review of every concept above",
    conceptFocus: "mixed-review",
    boss: { name: "The Mastermind", emoji: "🎩", reward: "Chief Detective Trophy" },
  },
];

export default WORLDS;
